package hw02.ball;

import java.awt.Graphics;
import java.awt.Rectangle;

import javax.swing.Timer;

import provided.utils.dispatcher.IDispatcher;
import provided.utils.dispatcher.IObserver;
import provided.utils.dispatcher.impl.SequentialDispatcher;
import provided.utils.loader.IObjectLoader;
import provided.utils.loader.impl.ObjectLoader;
import provided.utils.valueGenerator.impl.Randomizer;

/**
 * @author rlmse
 * A model representing a collection of independently moving balls in a 2D plane
 */
public class BallModel {
	/**
	 * The period of the model refresh, in milliseconds
	 */
	private static final int timeSlice = 50;

	/**
	 * An adapter that allows the model to communicate with the view that will display it 
	 */
	private IModel2ViewAdapter model2ViewAdpt = IModel2ViewAdapter.NULL_OBJECT; // Insures that the adapter is always valid

	/**
	 * A timer that tells the view to refresh according to the rate set by the model
	 */
	private Timer timer = new Timer(timeSlice, (e) -> model2ViewAdpt.update());

	/**
	 * A dispatcher which tells the balls generated by the model to update
	 */
	private IDispatcher<Graphics> ballDispatcher = new SequentialDispatcher<Graphics>();

	/**
	 * An object used to load in the correct type of ABall, according to input from the view
	 */
	private final IObjectLoader<IObserver<Graphics>> loader = new ObjectLoader<IObserver<Graphics>>(
			args -> new ErrorBall(model2ViewAdpt.getDimension()));

	/**
	 * Construct a new model
	 * @param model2ViewAdpt - the adapter allowing the model to communicate with the view
	 */
	public BallModel(IModel2ViewAdapter model2ViewAdpt) {
		this.model2ViewAdpt = model2ViewAdpt;
	}

	/**
	 * Tells the dispatcher to update the balls in the model
	 * @param g - the Graphics object containing the balls that the model has generated
	 */
	public void update(Graphics g) {
		ballDispatcher.updateAll(g);
	}

	/**
	 * @return the period of the model refresh
	 */
	public static int getTimeSlice() {
		return timeSlice;
	}

	/**
	 * Generates an ABall
	 * @param ballType - the type of ABall to be generated. Input from the view
	 */
	public void makeBall(String ballType) {
		IObserver<Graphics> ball = this.loader.loadInstance(ballType, Randomizer.Singleton.randomColor(),
				Randomizer.Singleton.randomLoc(new Rectangle(this.model2ViewAdpt.getDimension().getWidth(),
						this.model2ViewAdpt.getDimension().getHeight())),
				Randomizer.Singleton.randomVel(new Rectangle(20, 20)), Randomizer.Singleton.randomInt(10, 20),
				this.model2ViewAdpt.getDimension());

		this.ballDispatcher.addObserver(ball);
	}

	/**
	 * Unsubscribe all current balls from the dispatcher, thus removing them from the view
	 */
	public void clearBalls() {
		this.ballDispatcher.removeAllObservers();
	}

	/**
	 * Start the timer of the model, thus beginning to update the status of the balls in the model
	 */
	public void start() {
		this.timer.start();
	}

}
