package hw02.view;

import java.awt.Graphics;

/**
 * @author rlmse
 * An adapter which allows the view to communicate to the model
 */
public interface IView2ModelAdapter {

	/**
	 * Tells the model to make a ball of the specified type
	 * @param ballType - the name of the type of ball that the model will generate
	 */
	public void makeBall(String ballType);

	/**
	 * Tells the model to delete the balls it has generated
	 */
	public void clearBalls();

	/**
	 * Tells the balls generated by the model to display themselves in the view
	 * @param g - the Graphics object on which the balls generated by the model are displayed
	 */
	public void paintBalls(Graphics g);
}
